name: StarSpawners
version: ${project.version}
main: com.starmediadev.plugins.starspawners.StarSpawners
api-version: 1.18
authors: [ AloneMusk ]
description: Spawner plugin for FirecraftMC
depend: [StarMCUtils]

commands:
  spawner:
    description: Spawners main command!
    usage: /<command>

