name: Spawners
version: ${project.version}
main: com.starmediadev.plugins.spawners.Spawners
api-version: 1.17
authors: [ AloneMusk ]
description: Spawner plugin for FirecraftMC

commands:
  spawner:
    description: Spawners main command!

